// Refactor note: styles extracted from page.tsx so the component file contains logic only.
// All visual tokens reference COLORS and MONO_FONT from config.ts.

import type { CSSProperties } from "react";
import { COLORS, MONO_FONT } from "../config";

export const styles: Record<string, CSSProperties> = {
  // ── Landing ───────────────────────────────────────────────────────────────
  landingContainer: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
    width: "100%",
  },
  hero: {
    height: "25vh",
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
    padding: "0 24px",
    textAlign: "center",
    background: COLORS.bgSurface,
  },
  heroEmoji:    { fontSize: "52px", lineHeight: "1" },
  heroTitle:    { fontSize: "42px", fontWeight: 800, color: COLORS.textPrimary, letterSpacing: "-0.5px" },
  heroSubtitle: { fontSize: "16px", color: COLORS.textSecondary, maxWidth: "360px", lineHeight: "1.5" },

  formSection: {
    flex: 1,
    overflowY: "auto",
    padding: "32px 24px 48px",
    borderTop: `1px solid ${COLORS.accentDim}`,
    background: COLORS.bgPrimary,
  },
  formCard: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    width: "100%",
    maxWidth: "440px",
    margin: "0 auto",
  },
  formLabel: { display: "block", fontSize: "15px", fontWeight: 600, color: COLORS.textPrimary, marginBottom: "8px" },
  formInput: {
    width: "100%",
    padding: "14px 16px",
    borderRadius: "12px",
    border: `1px solid ${COLORS.accentDim}`,
    background: COLORS.bgSurface,
    color: COLORS.textPrimary,
    fontSize: "16px",
    outline: "none",
    transition: "border-color 200ms ease",
    boxSizing: "border-box",
  },
  formHint: { fontSize: "11px", color: COLORS.textSecondary, marginTop: "6px" },

  // ── API key field ─────────────────────────────────────────────────────────
  apiKeyWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  apiKeyInput: {
    width: "100%",
    padding: "14px 70px 14px 16px",
    borderRadius: "12px",
    border: `1px solid ${COLORS.accentDim}`,
    background: COLORS.bgSurface,
    color: COLORS.textPrimary,
    fontSize: "16px",
    outline: "none",
    transition: "border-color 200ms ease",
    boxSizing: "border-box",
    fontFamily: MONO_FONT,
    letterSpacing: "0.04em",
  },
  apiKeyToggle: {
    position: "absolute",
    right: "10px",
    padding: "5px 10px",
    background: "transparent",
    border: `1px solid ${COLORS.accentDim}`,
    borderRadius: "6px",
    color: COLORS.textSecondary,
    fontSize: "12px",
    cursor: "pointer",
    transition: "all 200ms ease",
    whiteSpace: "nowrap",
  },

  // ── Coach selector ────────────────────────────────────────────────────────
  selectorLabel: { fontSize: "15px", fontWeight: 600, color: COLORS.textPrimary, marginBottom: "10px" },
  pillGroup:     { display: "flex", justifyContent: "center", flexWrap: "wrap", gap: "8px" },
  pill: {
    padding: "7px 16px",
    borderRadius: "20px",
    border: `1px solid ${COLORS.accentDim}`,
    background: "transparent",
    color: COLORS.textSecondary,
    fontSize: "14px",
    cursor: "pointer",
    transition: "all 200ms ease",
    whiteSpace: "nowrap",
  },
  pillActive: {
    padding: "7px 16px",
    borderRadius: "20px",
    border: `1px solid ${COLORS.accent}`,
    background: COLORS.accent,
    color: COLORS.textPrimary,
    fontSize: "14px",
    cursor: "pointer",
    transition: "all 200ms ease",
    whiteSpace: "nowrap",
  },
  selectorDesc: { fontSize: "12px", color: COLORS.textSecondary, marginTop: "8px", minHeight: "16px" },

  // ── Advanced options ──────────────────────────────────────────────────────
  advancedToggle: {
    background: "transparent",
    border: "none",
    color: COLORS.accent,
    fontSize: "14px",
    cursor: "pointer",
    padding: "4px 0",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    transition: "opacity 200ms ease",
  },
  advancedPanel: {
    marginTop: "14px",
    padding: "20px",
    background: COLORS.bgSurface,
    borderRadius: "12px",
    border: `1px solid ${COLORS.accentDim}`,
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  advancedRow:      { display: "flex", flexDirection: "column", gap: "8px" },
  advancedLabelRow: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  advancedLabel:    { fontSize: "13px", fontWeight: 600, color: COLORS.textPrimary },
  advancedValue:    { fontSize: "13px", color: COLORS.accent, fontFamily: MONO_FONT },
  advancedSelect: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: "8px",
    border: `1px solid ${COLORS.accentDim}`,
    background: COLORS.bgPrimary,
    color: COLORS.textPrimary,
    fontSize: "14px",
    outline: "none",
    cursor: "pointer",
  },
  advancedSlider: { width: "100%", accentColor: COLORS.accent, cursor: "pointer" },
  sliderHints:    { display: "flex", justifyContent: "space-between", fontSize: "11px", color: COLORS.textSecondary },

  // ── Start button ──────────────────────────────────────────────────────────
  startButton: {
    padding: "14px",
    borderRadius: "12px",
    border: "none",
    background: COLORS.accent,
    color: COLORS.textPrimary,
    fontSize: "16px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "background 200ms ease",
    boxShadow: `0 4px 24px ${COLORS.shadowAccentMd}`,
  },
  startButtonDisabled: {
    background: COLORS.accentDim,
    color: COLORS.textSecondary,
    cursor: "not-allowed",
    boxShadow: "none",
  },

  // ── Chat layout ───────────────────────────────────────────────────────────
  chatContainer: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    maxWidth: "760px",
    margin: "0 auto",
    width: "100%",
    position: "relative",
  },
  header: {
    padding: "20px 24px 16px",
    borderBottom: `1px solid ${COLORS.accentDim}`,
    background: COLORS.bgSurface,
    borderRadius: "0 0 12px 12px",
    boxShadow: `0 4px 24px ${COLORS.shadowAccent}`,
  },
  headerRow:      { display: "flex", alignItems: "center", justifyContent: "space-between" },
  headerTitle:    { fontSize: "22px", fontWeight: 700, color: COLORS.textPrimary },
  headerSubtitle: { fontSize: "13px", color: COLORS.textSecondary, marginTop: "2px" },
  newSessionButton: {
    padding: "7px 14px",
    borderRadius: "8px",
    border: `1px solid ${COLORS.accentDim}`,
    background: "transparent",
    color: COLORS.textSecondary,
    fontSize: "13px",
    cursor: "pointer",
    transition: "all 200ms ease",
  },
  infoButton: {
    padding: "6px 10px",
    borderRadius: "8px",
    border: `1px solid ${COLORS.accentDim}`,
    background: "transparent",
    color: COLORS.accent,
    fontSize: "16px",
    cursor: "pointer",
    lineHeight: "1",
    transition: "all 200ms ease",
  },

  // ── Session info panel ────────────────────────────────────────────────────
  infoPanel: {
    position: "absolute",
    top: "72px",
    right: "16px",
    width: "260px",
    background: COLORS.bgSurface,
    border: `1px solid ${COLORS.accentDim}`,
    borderRadius: "12px",
    padding: "16px",
    boxShadow: `0 8px 32px ${COLORS.shadowHeavy}`,
    zIndex: 100,
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  infoPanelTitle:   { fontSize: "13px", fontWeight: 700, color: COLORS.textPrimary, margin: 0 },
  infoSection:      { display: "flex", flexDirection: "column", gap: "8px" },
  infoSectionTitle: {
    fontSize: "10px",
    fontWeight: 600,
    color: COLORS.textSecondary,
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    margin: 0,
  },
  infoRow:   { display: "flex", justifyContent: "space-between", alignItems: "center" },
  infoLabel: { fontSize: "13px", color: COLORS.textSecondary },
  infoValue: { fontSize: "13px", color: COLORS.textPrimary, fontFamily: MONO_FONT },
  infoDivider: { height: "1px", background: COLORS.accentDim },

  // ── Message list ──────────────────────────────────────────────────────────
  messageListWrapper: { flex: 1, position: "relative", overflow: "hidden" },
  scrollToBottomBtn: {
    position: "absolute",
    bottom: "16px",
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 10,
    padding: "6px 16px",
    borderRadius: "20px",
    border: `1px solid ${COLORS.accentDim}`,
    background: COLORS.bgSurface,
    color: COLORS.accent,
    fontSize: "16px",
    cursor: "pointer",
    boxShadow: `0 4px 16px ${COLORS.shadowMedium}`,
    transition: "all 200ms ease",
  },
  messageList: {
    height: "100%",
    overflowY: "auto",
    padding: "24px 16px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  messageBubble: {
    padding: "12px 16px",
    borderRadius: "18px",
    maxWidth: "75%",
    lineHeight: "1.6",
    fontSize: "15px",
    wordBreak: "break-word",
    transition: "all 200ms ease",
  },
  userBubble: {
    background: COLORS.accent,
    color: COLORS.textPrimary,
    borderBottomRightRadius: "4px",
    boxShadow: `0 4px 24px ${COLORS.shadowAccent}`,
  },
  assistantBubble: {
    background: COLORS.accentDim,
    color: COLORS.textPrimary,
    borderBottomLeftRadius: "4px",
    boxShadow: `0 4px 24px ${COLORS.shadowAccent}`,
  },
  messageTime: { fontSize: "11px", color: COLORS.textSecondary, padding: "0 4px" },
  typingDots:  { display: "inline-flex", gap: "4px", alignItems: "center", fontSize: "20px", color: COLORS.textSecondary },

  // ── Export button & dropdown ──────────────────────────────────────────────
  exportButtonWrap: {
    position: "relative" as const,
  },
  exportMenu: {
    position: "absolute" as const,
    top: "calc(100% + 6px)",
    right: 0,
    background: COLORS.bgSurface,
    border: `1px solid ${COLORS.accentDim}`,
    borderRadius: "10px",
    padding: "6px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "2px",
    zIndex: 200,
    minWidth: "140px",
    boxShadow: `0 8px 24px rgba(0,0,0,0.5)`,
  },
  exportMenuItem: {
    padding: "8px 14px",
    borderRadius: "7px",
    border: "none",
    background: "transparent",
    color: COLORS.textPrimary,
    fontSize: "14px",
    cursor: "pointer",
    textAlign: "left" as const,
    transition: "background 150ms ease",
    width: "100%",
    display: "flex",
    gap: "8px",
    alignItems: "center",
  },

  // ── Input bar ─────────────────────────────────────────────────────────────
  inputArea: {
    display: "flex",
    gap: "10px",
    padding: "16px",
    borderTop: `1px solid ${COLORS.accentDim}`,
    background: COLORS.bgSurface,
    alignItems: "flex-end",
    borderRadius: "12px 12px 0 0",
    boxShadow: `0 4px 24px ${COLORS.shadowAccent}`,
  },
  textarea: {
    flex: 1,
    padding: "12px 14px",
    borderRadius: "12px",
    border: `1px solid ${COLORS.accentDim}`,
    fontSize: "15px",
    resize: "none",
    outline: "none",
    fontFamily: "inherit",
    color: COLORS.textPrimary,
    background: COLORS.bgPrimary,
    lineHeight: "1.5",
    minHeight: "48px",
    maxHeight: "140px",
    overflowY: "hidden",
    transition: "border-color 200ms ease",
  },
  sendButton: {
    padding: "0 22px",
    borderRadius: "12px",
    border: "none",
    background: COLORS.accent,
    color: COLORS.textPrimary,
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "background 200ms ease",
    alignSelf: "stretch",
  },
  sendButtonDisabled: { background: COLORS.accentDim, color: COLORS.textSecondary, cursor: "not-allowed" },

  // ── Breathing widget card ─────────────────────────────────────────────────
  // Renders before the assistant text bubble that introduces the exercise.
  breathingCard: {
    width: "100%",
    maxWidth: "300px",
    padding: "20px 20px 16px",
    background: COLORS.bgSurface,
    borderRadius: "16px",
    border: `1px solid ${COLORS.accentDim}`,
    boxShadow: `0 4px 24px ${COLORS.shadowAccent}`,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "14px",
  },
  breathingHeader: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "4px",
    textAlign: "center" as const,
  },
  breathingTitle: {
    fontSize: "11px",
    fontWeight: 700,
    color: COLORS.accent,
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
  },
  breathingReason: {
    fontSize: "12px",
    color: COLORS.textSecondary,
    textAlign: "center" as const,
    lineHeight: "1.5",
    maxWidth: "240px",
  },
  breathingCircleWrap: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "16px",  // room for the pulse ring to expand outward
  },
  breathingCircle: {
    width: "112px",
    height: "112px",
    borderRadius: "50%",
    background: `radial-gradient(circle at 40% 35%, ${COLORS.accent}, ${COLORS.accentDim})`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    willChange: "transform",
  },
  breathingLabel: {
    fontSize: "13px",
    fontWeight: 600,
    color: COLORS.textPrimary,
    textAlign: "center" as const,
    letterSpacing: "0.02em",
    userSelect: "none" as const,
  },
  breathingSubtitle: {
    fontSize: "11px",
    color: COLORS.textSecondary,
    fontFamily: MONO_FONT,
    letterSpacing: "0.04em",
  },
  breathingControls: {
    display: "flex",
    gap: "8px",
  },
  breathingBtn: {
    padding: "7px 18px",
    borderRadius: "10px",
    border: `1px solid ${COLORS.accentDim}`,
    background: "transparent",
    color: COLORS.textSecondary,
    fontSize: "13px",
    cursor: "pointer",
    transition: "all 200ms ease",
  },
  breathingBtnPrimary: {
    padding: "7px 24px",
    borderRadius: "10px",
    border: "none",
    background: COLORS.accent,
    color: COLORS.textPrimary,
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 200ms ease",
  },
  breathingDoneToast: {
    width: "100%",
    padding: "14px 16px",
    background: "rgba(148, 114, 182, 0.08)",
    borderRadius: "12px",
    border: "1px solid rgba(148, 114, 182, 0.18)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "10px",
  },
  breathingDoneTitle: {
    fontSize: "13px",
    fontWeight: 600,
    color: COLORS.textPrimary,
    textAlign: "center" as const,
  },
  breathingAck: {
    fontSize: "12px",
    color: COLORS.textSecondary,
    textAlign: "center" as const,
  },
  breathingMoodRow: {
    display: "flex",
    gap: "6px",
    flexWrap: "wrap" as const,
    justifyContent: "center",
  },
  breathingMoodBtn: {
    padding: "5px 12px",
    borderRadius: "20px",
    border: `1px solid ${COLORS.accentDim}`,
    background: "transparent",
    color: COLORS.textPrimary,
    fontSize: "12px",
    cursor: "pointer",
    transition: "all 200ms ease",
  },

  // ── Reframe thought card ─────────────────────────────────────────────────
  reframeCard: {
    width: "100%",
    maxWidth: "520px",
    padding: "20px",
    background: COLORS.bgSurface,
    borderRadius: "16px",
    border: `1px solid ${COLORS.accentDim}`,
    boxShadow: `0 4px 24px ${COLORS.shadowAccent}`,
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  reframeDistortionPill: {
    alignSelf: "flex-start",
    padding: "4px 12px",
    borderRadius: "20px",
    border: `1px solid ${COLORS.accent}`,
    background: "rgba(148, 114, 182, 0.10)",
    color: COLORS.accent,
    fontSize: "11px",
    fontWeight: 700,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    cursor: "pointer",
    transition: "all 200ms ease",
  },
  reframeDefinition: {
    fontSize: "12px",
    color: COLORS.textSecondary,
    fontStyle: "italic" as const,
    lineHeight: "1.5",
    marginTop: "-6px",
  },
  reframePanels: {
    display: "flex",
    alignItems: "stretch",
  },
  reframePanel: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "0 14px",
  },
  reframePanelDivider: {
    width: "1px",
    background: COLORS.accentDim,
    alignSelf: "stretch",
    flexShrink: 0,
  },
  reframePanelLabel: {
    fontSize: "10px",
    fontWeight: 600,
    color: COLORS.textSecondary,
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
  },
  reframeOriginal: {
    fontSize: "14px",
    fontStyle: "italic" as const,
    color: COLORS.textSecondary,
    lineHeight: "1.55",
  },
  reframeReframe: {
    fontSize: "14px",
    fontWeight: 700,
    color: COLORS.textPrimary,
    lineHeight: "1.55",
  },
  reframeEvidenceSection: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    borderTop: `1px solid ${COLORS.accentDim}`,
    paddingTop: "12px",
  },
  reframeEvidenceTitle: {
    fontSize: "10px",
    fontWeight: 600,
    color: COLORS.textSecondary,
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
  },
  reframeEvidenceList: {
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    padding: 0,
    margin: 0,
  },
  reframeEvidenceItem: {
    fontSize: "13px",
    color: COLORS.textPrimary,
    lineHeight: "1.5",
  },

  // ── Prep for situation card ───────────────────────────────────────────────
  prepCard: {
    width: "100%",
    maxWidth: "580px",
    background: COLORS.bgSurface,
    borderRadius: "16px",
    border: `1px solid ${COLORS.accentDim}`,
    boxShadow: `0 4px 24px ${COLORS.shadowAccent}`,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  prepHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "16px 20px",
    borderBottom: `1px solid ${COLORS.accentDim}`,
  },
  prepSituationPill: {
    padding: "3px 10px",
    borderRadius: "20px",
    border: `1px solid ${COLORS.accent}`,
    background: "rgba(148, 114, 182, 0.10)",
    color: COLORS.accent,
    fontSize: "11px",
    fontWeight: 700,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    flexShrink: 0,
  },
  prepEventDesc: {
    flex: 1,
    fontSize: "14px",
    fontWeight: 600,
    color: COLORS.textPrimary,
    lineHeight: "1.4",
  },
  prepSection: {
    padding: "16px 20px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    borderBottom: `1px solid ${COLORS.accentDim}`,
  },
  prepSectionTitle: {
    fontSize: "10px",
    fontWeight: 600,
    color: COLORS.textSecondary,
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
  },
  prepWorryRow: {
    display: "flex",
    gap: "10px",
    alignItems: "flex-start",
  },
  prepWorryText: {
    flex: 1,
    fontSize: "13px",
    color: COLORS.textSecondary,
    fontStyle: "italic" as const,
    lineHeight: "1.5",
    margin: 0,
  },
  prepArrow: {
    fontSize: "13px",
    color: COLORS.accent,
    flexShrink: 0,
    paddingTop: "1px",
  },
  prepReframeText: {
    flex: 1,
    fontSize: "13px",
    color: COLORS.textPrimary,
    lineHeight: "1.5",
    margin: 0,
  },
  prepAnchorRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    cursor: "pointer",
    userSelect: "none" as const,
  },
  prepAnchorText: {
    fontSize: "13px",
    color: COLORS.textPrimary,
    lineHeight: "1.5",
    transition: "all 200ms ease",
  },
  prepTabRow: {
    display: "flex",
    gap: "6px",
    flexWrap: "wrap" as const,
  },
  prepTab: {
    padding: "4px 14px",
    borderRadius: "20px",
    border: `1px solid ${COLORS.accentDim}`,
    background: "transparent",
    color: COLORS.textSecondary,
    fontSize: "12px",
    cursor: "pointer",
    transition: "all 200ms ease",
  },
  prepTabActive: {
    padding: "4px 14px",
    borderRadius: "20px",
    border: `1px solid ${COLORS.accent}`,
    background: "rgba(148, 114, 182, 0.15)",
    color: COLORS.accent,
    fontSize: "12px",
    fontWeight: 700,
    cursor: "pointer",
    transition: "all 200ms ease",
  },
  prepScriptWrap: {
    position: "relative" as const,
  },
  prepScriptBlock: {
    fontSize: "13px",
    color: COLORS.textPrimary,
    lineHeight: "1.6",
    padding: "12px 48px 12px 14px",
    background: COLORS.bgPrimary,
    borderRadius: "10px",
    border: `1px solid ${COLORS.accentDim}`,
    margin: 0,
    whiteSpace: "pre-wrap" as const,
  },
  prepCopyBtn: {
    position: "absolute" as const,
    top: "8px",
    right: "8px",
    padding: "3px 8px",
    borderRadius: "6px",
    border: `1px solid ${COLORS.accentDim}`,
    background: COLORS.bgSurface,
    color: COLORS.textSecondary,
    fontSize: "11px",
    cursor: "pointer",
    transition: "all 200ms ease",
  },
  prepFooter: {
    padding: "14px 20px",
    display: "flex",
    justifyContent: "flex-end",
  },
  prepSaveBtn: {
    padding: "7px 18px",
    borderRadius: "10px",
    border: "none",
    background: COLORS.accent,
    color: COLORS.textPrimary,
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 200ms ease",
  },
  prepSavedBtn: {
    padding: "7px 18px",
    borderRadius: "10px",
    border: `1px solid ${COLORS.accentDim}`,
    background: "transparent",
    color: COLORS.textSecondary,
    fontSize: "13px",
    cursor: "default",
  },

  // ── Professional support widget ──────────────────────────────────────────
  // Shared card container for all stages (form / loading / results / error).
  supportCard: {
    width: "100%",
    maxWidth: "520px",
    background: COLORS.bgSurface,
    borderRadius: "16px",
    border: `1px solid ${COLORS.accentDim}`,
    boxShadow: `0 4px 24px ${COLORS.shadowAccent}`,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },

  // Stage: form
  supportFormHeader: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    padding: "18px 20px 14px",
    borderBottom: `1px solid ${COLORS.accentDim}`,
  },
  supportFormTitle: {
    fontSize: "15px",
    fontWeight: 700,
    color: COLORS.textPrimary,
    lineHeight: "1.4",
  },
  supportFormSubtitle: {
    fontSize: "12px",
    color: COLORS.textSecondary,
    lineHeight: "1.4",
  },
  supportFormBody: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    padding: "16px 20px 20px",
  },
  supportFormRow: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  supportFormLabel: {
    fontSize: "12px",
    fontWeight: 600,
    color: COLORS.textPrimary,
    letterSpacing: "0.02em",
  },
  supportFormInput: {
    padding: "10px 12px",
    borderRadius: "10px",
    border: `1px solid ${COLORS.accentDim}`,
    background: COLORS.bgPrimary,
    color: COLORS.textPrimary,
    fontSize: "14px",
    outline: "none",
    transition: "border-color 200ms ease",
    boxSizing: "border-box" as const,
    width: "100%",
  },
  supportSubmitBtn: {
    alignSelf: "flex-end" as const,
    padding: "9px 20px",
    borderRadius: "10px",
    border: "none",
    background: COLORS.accent,
    color: COLORS.textPrimary,
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 200ms ease",
  },
  supportSubmitBtnDisabled: {
    background: COLORS.accentDim,
    color: COLORS.textSecondary,
    cursor: "not-allowed",
  },

  // Stage: loading
  supportLoadingWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "12px",
    padding: "28px 20px",
  },
  supportLoadingText: {
    fontSize: "13px",
    color: COLORS.textSecondary,
    textAlign: "center" as const,
    lineHeight: "1.5",
  },

  // Stage: error
  supportErrorWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "14px",
    padding: "24px 20px",
  },
  supportErrorText: {
    fontSize: "13px",
    color: COLORS.warningText,
    textAlign: "center" as const,
    lineHeight: "1.5",
  },

  // Stage: results — crisis strip (always at top)
  supportCrisisStrip: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap" as const,
    gap: "8px",
    padding: "10px 20px",
    background: "rgba(148, 114, 182, 0.06)",
    borderBottom: `1px solid ${COLORS.accentDim}`,
  },
  supportCrisisLabel: {
    fontSize: "11px",
    fontWeight: 700,
    color: COLORS.textSecondary,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
  },
  supportCrisisName: {
    fontSize: "12px",
    color: COLORS.textPrimary,
    fontWeight: 600,
  },
  supportCrisisNumber: {
    fontSize: "12px",
    color: COLORS.accent,
    fontWeight: 700,
  },
  supportCrisisLink: {
    fontSize: "12px",
    color: COLORS.accent,
    textDecoration: "none" as const,
    fontWeight: 600,
    transition: "opacity 200ms ease",
  },

  // Results header
  supportResultsHeader: {
    fontSize: "13px",
    color: COLORS.textSecondary,
    padding: "14px 20px 6px",
    lineHeight: "1.4",
  },

  // No results fallback
  supportNoResults: {
    fontSize: "13px",
    color: COLORS.textSecondary,
    padding: "16px 20px",
    lineHeight: "1.5",
    fontStyle: "italic" as const,
  },

  // Individual result card
  supportResultCard: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "14px 20px",
    borderTop: `1px solid ${COLORS.accentDim}`,
  },
  supportResultTop: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "10px",
    flexWrap: "wrap" as const,
  },
  supportResultName: {
    fontSize: "14px",
    fontWeight: 700,
    color: COLORS.textPrimary,
    lineHeight: "1.4",
    flex: 1,
  },
  supportResultTagRow: {
    display: "flex",
    gap: "6px",
    flexShrink: 0,
    flexWrap: "wrap" as const,
  },
  supportResultTag: {
    padding: "2px 8px",
    borderRadius: "20px",
    border: `1px solid ${COLORS.accentDim}`,
    background: "transparent",
    color: COLORS.textSecondary,
    fontSize: "11px",
    fontWeight: 600,
  },
  supportResultFormatTag: {
    padding: "2px 8px",
    borderRadius: "20px",
    border: `1px solid ${COLORS.accent}`,
    background: "rgba(148, 114, 182, 0.10)",
    color: COLORS.accent,
    fontSize: "11px",
    fontWeight: 600,
  },
  supportResultDesc: {
    fontSize: "13px",
    color: COLORS.textSecondary,
    lineHeight: "1.5",
    margin: 0,
  },
  supportResultLink: {
    alignSelf: "flex-end" as const,
    fontSize: "12px",
    color: COLORS.accent,
    fontWeight: 600,
    textDecoration: "none" as const,
    padding: "4px 10px",
    borderRadius: "8px",
    border: `1px solid ${COLORS.accent}`,
    transition: "all 200ms ease",
  },

  // Results footer
  supportResultsFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    padding: "12px 20px 16px",
    borderTop: `1px solid ${COLORS.accentDim}`,
    flexWrap: "wrap" as const,
  },
  supportDisclaimer: {
    fontSize: "11px",
    color: COLORS.textSecondary,
    lineHeight: "1.4",
    flex: 1,
  },
  supportSearchAgainBtn: {
    padding: "5px 14px",
    borderRadius: "8px",
    border: `1px solid ${COLORS.accentDim}`,
    background: "transparent",
    color: COLORS.textSecondary,
    fontSize: "12px",
    cursor: "pointer",
    transition: "all 200ms ease",
    flexShrink: 0,
  },

  // ── Message limit warning bar ─────────────────────────────────────────────
  limitWarningBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    padding: "10px 16px",
    borderTop: `1px solid ${COLORS.warningBorder}`,
    background: COLORS.bgSurface,
  },
  limitWarningText:    { fontSize: "13px", color: COLORS.warningText, flex: 1 },
  limitWarningActions: { display: "flex", gap: "8px", flexShrink: 0 },
  limitCancelBtn: {
    padding: "5px 12px",
    borderRadius: "8px",
    border: `1px solid ${COLORS.accentDim}`,
    background: "transparent",
    color: COLORS.textSecondary,
    fontSize: "13px",
    cursor: "pointer",
  },
  limitConfirmBtn: {
    padding: "5px 12px",
    borderRadius: "8px",
    border: "none",
    background: COLORS.accent,
    color: COLORS.textPrimary,
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
  },
};
